// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mmuxdhhfqryxgrhekqkd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1tdXhkaGhmcXJ5eGdyaGVrcWtkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYzNjc3ODIsImV4cCI6MjA1MTk0Mzc4Mn0.bbBGUF1Au_brFKWBr9FQEY3ab371at4nq5mA6UZnOo8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);